

CREATE TABLE supplychaindataset(
							Type VARCHAR(50),
							Days_for_shipping_real INT,
							Days_for_shipment_scheduled INT,
							Benefit_per_order NUMERIC(12, 8),
							Sales_per_customer FLOAT,
							Delivery_Status VARCHAR(100),
							Late_delivery_risk INT,
							Category_Id INT,
							Category_Name VARCHAR(100),
							Customer_City VARCHAR(100),
							Customer_Country VARCHAR(100),
							Customer_Email VARCHAR(100),
							Customer_Fname VARCHAR(100),
							Customer_Id INT,
							Customer_Lname VARCHAR(100),
							Customer_Password VARCHAR(100),
							Customer_Segment VARCHAR(100),
							Customer_State VARCHAR(100),
							Customer_Street	VARCHAR(100),
							Customer_Zipcode INT,
							Department_Id INT,	
							Department_Name	VARCHAR(100),
							Latitude NUMERIC(12, 8),
							Longitude NUMERIC(12, 8),
							Market VARCHAR(100),
							Order_City VARCHAR(100),
							Order_Country VARCHAR(100),
							Order_Customer_Id INT,
							order_date_DateOrders DATE,
							Order_Id INT,
							Order_Item_Cardprod_Id INT,
							Order_Item_Discount	FLOAT,
							Order_Item_Discount_Rate FLOAT,
							Order_Item_Id INT,
							Order_Item_Product_Price FLOAT,
							Order_Item_Profit_RatioB NUMERIC(12, 8),
							Order_Item_Quantity INT,
							Sales FLOAT,
							Order_Item_Total NUMERIC(12, 8),
							Order_Profit_Per_Order NUMERIC(12, 8),
							Order_Region VARCHAR(100),
							Order_State VARCHAR(100),
							Order_Status VARCHAR(100),
							Order_Zipcode INT,
							Product_Card_Id INT,
							Product_Category_Id INT,
							Product_Description VARCHAR(20),
							Product_Image VARCHAR(1000),
							Product_Name VARCHAR(100),
							Product_Price FLOAT,
							Product_Status INT,
							shipping_date_DateOrders DATE,
							Shipping_Mode VARCHAR(100)

);

